---
- hosts: web
  remote_user: ec2-user
  become: yes
  become_method: sudo 
  
  tasks:
    - name:  Docker pull
      shell: docker pull public.ecr.aws/e7w1y6p1/demo

    - name:  Docker run
      shell: docker run --name nginx -d -p 8080:80 nginx
